/* Bravura notation and rhythm editor. Playback stays with the existing engine. */
(()=>{
 const panel=document.querySelector('.panel-visu'),wrapper=panel.querySelector('.sequencer-wrapper'),metronomeButton=document.getElementById('scoreMetronomeBtn'),partitionButton=document.getElementById('scorePartitionBtn');
 const viewSwitch=document.getElementById("scoreViewSwitch");wrapper.prepend(viewSwitch);
 for(const button of [metronomeButton,partitionButton]){for(const node of [...button.childNodes])if(node.nodeType===Node.TEXT_NODE)node.remove();button.title=button.getAttribute("aria-label");}
 const host=document.createElement('div');host.className='rhythm-score';host.id='rhythmScore';host.setAttribute('role','img');host.setAttribute('aria-label','Partition rythmique, police Bravura');wrapper.append(host);
 let enabled=false,loading,Flow,core,lastKey='',notes=new Map(),cues=[],active=[],frame=0,redraw=0,pulseAnchors=[],pulseBeat=0,pulseLineY=0;
 const status=text=>{host.replaceChildren();const p=document.createElement('div');p.className='rhythm-score-status';p.textContent=text;host.append(p);};
 async function load(){if(!loading)loading=Promise.all([import('./rhythm-editor-core.mjs?v=20261010-paired-groups1'),new Promise((resolve,reject)=>{if(window.Vex)return resolve();const script=document.createElement('script');script.src='vendor/vexflow-bravura-4.2.5.js';script.onload=resolve;script.onerror=()=>{script.remove();reject(new Error('Impossible de charger la partition. Réessaie avec Partition.'));};document.head.append(script);})]).then(([module])=>{core=module;Flow=window.Vex.Flow||window.Vex;Flow.setMusicFont('Bravura');}).catch(error=>{loading=null;throw error;});return loading;}

 const colors=['#80858e','var(--cyan)','var(--yellow)','var(--orange)'];
 let editing=false,selected=null,selectedMeasure=null;
 const pencil=document.createElement('button');pencil.id='scoreEditBtn';pencil.type='button';pencil.title='Éditer la partition';pencil.setAttribute('aria-label','Éditer la partition');pencil.setAttribute('aria-pressed','false');pencil.hidden=true;pencil.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m4 16 11-11 4 4L8 20H4v-4ZM13 7l4 4M15 5l2-2 4 4-2 2"/></svg>';viewSwitch.append(pencil);
 const editor=document.createElement('div');editor.id='rhythmEditor';editor.className='rhythm-editor';editor.hidden=true;editor.setAttribute('aria-label','Outils de partition');const toolsPanel=document.createElement('div');toolsPanel.className='score-tools-panel';wrapper.insertBefore(toolsPanel,host);toolsPanel.append(viewSwitch,editor);
 const pulse=document.createElement('div');pulse.className='score-pulse';pulse.hidden=true;pulse.setAttribute('aria-label','Pulsation');pulse.innerHTML='<span></span>';wrapper.append(pulse);
 const frozen=new WeakMap(),scheduling=getSchedulingMeasure;
 getSchedulingMeasure=function(m){const result=scheduling(m),saved=frozen.get(m);if(saved&&saved.layout===scheduledMeasureLayouts.get(m))return {...result,beatStates:saved.states};frozen.delete(m);return result;};
 function save(model){const m=measures[activeMeasureIndex];if(isPlaying&&!frozen.has(m)&&scheduledMeasureLayouts.has(m)){const current=scheduling(m);frozen.set(m,{layout:scheduledMeasureLayouts.get(m),states:current.beatStates.map(s=>[...s])});}core.commitModel(m,model);lastKey='';renderActiveMeasure();refreshMeasurePreviews();refreshBeatEditor();draw();renderEditor();layout();}
 function selectEvent(index){if(!editing)return;selected=index;selectedMeasure=measures[activeMeasureIndex];const m=selectedMeasure,event=core.editorModel(m).events[index];if(event)save(core.changeEvent(m,index,{state:(event.state+1)%4}));}

 function button(text,fn,parent=editor){const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=fn;parent.append(b);return b;}
 function attempt(fn){try{fn();}catch(error){message.textContent=error.message;}}
 const message=document.createElement('p');message.className='score-editor-message';message.setAttribute('role','status');
 function renderEditor(){editor.replaceChildren();if(!editing||appMode!=='metronome'||!core)return;const m=measures[activeMeasureIndex],model=core.editorModel(m);if(selectedMeasure!==m){selected=null;selectedMeasure=m;}const event=model.events[selected];
  const title=document.createElement('p');title.className='score-editor-title';title.textContent=event?(event.state?'Note':'Silence')+' '+(selected+1)+' · durée '+Number((event.end-event.start).toFixed(4))+' unité(s)':'Sélectionne une note ou un silence';editor.append(title);
  const body=document.createElement('div');body.className='score-editor-body';editor.append(body);const tools=document.createElement('div');tools.className='score-duration-tools';tools.setAttribute('aria-label','Durées : simples en haut, pointées en bas');body.append(tools);
  for(const [value,label] of [[1,'Ronde'],[2,'Blanche'],[4,'Noire'],[8,'Croche'],[16,'Double'],[32,'Triple']])for(const dotted of [false,true]){const length=m.denominator/value*(dotted?1.5:1),b=button(label+(dotted?' ·':''),()=>attempt(()=>save(core.changeEvent(m,selected,{length}))),tools);const icon=document.createElementNS('http://www.w3.org/2000/svg','svg');icon.setAttribute('viewBox','0 0 26 24');icon.setAttribute('aria-hidden','true');icon.innerHTML='<ellipse cx="10" cy="18" rx="4" ry="2.8" transform="rotate(-20 10 18)" fill="'+(value<=2?'none':'currentColor')+'" stroke="currentColor"/>'+(value>=2?'<path d="M14 17V3"/>':'')+(value>=8?Array.from({length:value===8?1:value===16?2:3},(_,i)=>'<path d="M14 '+(3+i*4)+'c6 3 6 6 3 8"/>').join(''):'')+(dotted?'<circle cx="21" cy="18" r="1.5" fill="currentColor" stroke="none"/>':'');b.textContent='';b.title=label+(dotted?' pointée':'');b.setAttribute('aria-label',b.title);b.setAttribute('aria-pressed',String(!!event&&Math.abs(event.end-event.start-length)<1e-8));b.prepend(icon);b.dataset.duration=value;b.dataset.dotted=String(dotted);b.disabled=!event;if(event){try{core.changeEvent(m,selected,{length});}catch{b.disabled=true;}}}
  if(event){const b=Math.floor(event.start),n=m.beatSubdivisions[b];if(n===3||n>=5&&n<=7)button('1 subdivision / '+n,()=>attempt(()=>save(core.changeEvent(m,selected,{length:1/n}))),tools);}
  const groupPanel=document.createElement('div');groupPanel.className='score-group-panel';body.append(groupPanel);const groupable=core.groupCombinations(m.numerator).length>0&&m.denominator>=8;
  if(groupable){const toggle=button('Regroupement libre',()=>attempt(()=>save(core.regroup(m,!model.custom,model.custom?core.defaultGroups(m):core.defaultGroups(m).every(n=>n===2||n===3)?core.defaultGroups(m):core.groupCombinations(m.numerator)[0]))),groupPanel);toggle.id='scoreGroupingToggle';toggle.setAttribute('aria-pressed',String(model.custom));const groups=document.createElement('div');groups.className='score-group-tools';groupPanel.append(groups);let start=0;model.groups.forEach((n,i)=>{const label=document.createElement('label');label.textContent='Groupe '+(i+1)+' · '+(start+1)+' ';const select=document.createElement('select');select.setAttribute('aria-label','Taille du groupe '+(i+1));for(const value of [2,3]){const option=new Option(String(value),String(value));const left=m.numerator-model.groups.slice(0,i).reduce((a,b)=>a+b,0)-value;option.disabled=left<0||!core.groupCombinations(left).length;select.append(option);}select.value=n;select.disabled=!model.custom;select.onchange=()=>attempt(()=>{const prefix=model.groups.slice(0,i),value=Number(select.value),left=m.numerator-prefix.reduce((a,b)=>a+b,0)-value;save(core.regroup(m,true,[...prefix,value,...core.groupCombinations(left)[0]]));});label.append(select);groups.append(label);start+=n;});}
  message.textContent=isPlaying?'Lecture en cours : application au prochain passage de la mesure.':'Allonger absorbe les éléments suivants du groupe. Raccourcir crée un silence.';editor.append(message);
 }
 function fitScore(){if(!enabled)return;const svg=host.querySelector('svg');if(!svg)return;const ws=getComputedStyle(wrapper),hs=getComputedStyle(host),controls=parseFloat(ws.getPropertyValue('--score-controls-height'))||75,w=Number(svg.getAttribute('width')),h=Number(svg.getAttribute('height')),available=wrapper.clientHeight-parseFloat(ws.paddingTop)-parseFloat(ws.paddingBottom)-controls-parseFloat(hs.paddingTop)-parseFloat(hs.paddingBottom)-10-(appMode==='metronome'?28:0),scale=Math.min((host.clientWidth-8)/w,Math.max(12,available)/h);svg.style.width=w*scale+'px';svg.style.height=h*scale+'px';svg.style.marginInline='auto';positionPulse();}
 function layout(){const style=getComputedStyle(wrapper),controls=toolsPanel.offsetHeight+10;wrapper.style.setProperty('--score-controls-height',controls+'px');wrapper.style.setProperty('--score-circle-space',`${Math.max(40,wrapper.clientHeight-controls-parseFloat(style.paddingTop)-parseFloat(style.paddingBottom))}px`);resizeCanvas();updateRingRadius();fitScore();refresh();}
 pencil.onclick=async()=>{await load();editing=!editing;pencil.classList.toggle('active',editing);pencil.setAttribute('aria-pressed',String(editing));editor.hidden=!editing;host.setAttribute('role',editing?'group':'img');selected=null;lastKey='';renderEditor();draw();layout();};
 let burstFrame=0,burstParticles=[],pulseMotion=null;
 const burstCanvas=document.createElement('canvas'),burstRatio=Math.min(2,window.devicePixelRatio||1);burstCanvas.width=90*burstRatio;burstCanvas.height=70*burstRatio;burstCanvas.setAttribute('aria-hidden','true');pulse.prepend(burstCanvas);const burstContext=burstCanvas.getContext('2d');burstContext.scale(burstRatio,burstRatio);
 function clearBurst(){pulseMotion?.cancel();pulseMotion=null;cancelAnimationFrame(burstFrame);burstFrame=0;burstParticles=[];burstContext.clearRect(0,0,90,70);}
 function drawBurst(now){burstFrame=0;burstContext.clearRect(0,0,90,70);for(const p of burstParticles){const t=Math.min(1,(now-p.start)/p.duration),travel=1-Math.pow(1-t,3);if(t<1){burstContext.globalAlpha=.55*Math.pow(1-t,2);burstContext.fillStyle='#000';burstContext.beginPath();burstContext.arc(45+Math.cos(p.angle)*p.distance*travel,35+Math.sin(p.angle)*p.distance*travel,p.size*(1-.35*t),0,Math.PI*2);burstContext.fill();}}burstParticles=burstParticles.filter(p=>now-p.start<p.duration);burstContext.globalAlpha=1;if(burstParticles.length)burstFrame=requestAnimationFrame(drawBurst);}
 function positionPulse(beat=pulseBeat){pulseBeat=beat;const svg=host.querySelector('svg');if(!svg||!pulseAnchors.length)return;const next=pulseAnchors.find(a=>a.beat>beat),previous=[...pulseAnchors].reverse().find(a=>a.beat<=beat)||pulseAnchors[0];const x=next?previous.x+(next.x-previous.x)*(beat-previous.beat)/(next.beat-previous.beat):previous.x;const bounds=svg.getBoundingClientRect(),container=host.getBoundingClientRect(),scale=bounds.width/Number(svg.getAttribute('width'));pulse.style.marginLeft=(bounds.left-container.left+host.scrollLeft-host.clientLeft-parseFloat(getComputedStyle(host).paddingLeft)+x*scale-35)+'px';pulse.style.transform='translateY('+(pulseLineY*scale+14-bounds.height-17)+'px)';pulse.dataset.beat=String(beat);}
 function pulseNow(beat){const m=measures[activeMeasureIndex],groups=m.denominator>=8&&m.numerator%3===0?Array(m.numerator/3).fill(3):m.denominator>=8&&m.numerator>=5&&m.numerator%2?[...Array((m.numerator-3)/2).fill(2),3]:Array(m.numerator).fill(1);let startBeat=0,units=1;for(const group of groups){if(startBeat===beat){units=group;break;}startBeat+=group;}const fadeMs=Math.min(420,getStepDurationMs(getEffectiveTempo(m),m.denominator,1)*units*.75);pulse.style.setProperty('--pulse-fade-duration',fadeMs+'ms');const previousBeat=pulseBeat,previousX=parseFloat(pulse.style.marginLeft);clearBurst();positionPulse(beat);const targetX=parseFloat(pulse.style.marginLeft);if(beat>previousBeat&&Number.isFinite(previousX)&&!matchMedia('(prefers-reduced-motion:reduce)').matches)pulseMotion=pulse.animate([{transform:pulse.style.transform+' translateX('+(previousX-targetX)+'px)'},{transform:pulse.style.transform}],{duration:Math.min(140,fadeMs*.4),easing:'cubic-bezier(.16,1,.3,1)'});pulse.classList.remove('pulsing');void pulse.offsetWidth;pulse.classList.add('pulsing');if(matchMedia('(prefers-reduced-motion:reduce)').matches)return;const start=performance.now();for(let i=0;i<12;i++)burstParticles.push({angle:Math.PI*2*(i+Math.random()*.5)/12,distance:7+Math.random()*11,size:.45+Math.random()*.4,start,duration:380+Math.random()*240});burstFrame=requestAnimationFrame(drawBurst);}


 function clearHeads(){for(const item of active)for(const head of item.heads)head.classList.remove('score-active-head');active=[];}
 function remember(note,key,state){const element=note.getSVGElement();const heads=element?Array.from(element.querySelectorAll('.vf-notehead')):[];notes.set(key,{heads,state});}
 function makeNote(duration,state){const note=new Flow.StaveNote({keys:['b/4'],clef:'percussion',duration:duration+(state?'':'r'),stem_direction:1});return note;}
 function draw(){
  if(!enabled||!Flow)return;const measure=measures[activeMeasureIndex];if(!measure)return;
  const width=Math.floor(host.clientWidth-10);if(width<100)return;
  const key=JSON.stringify([appMode,activeMeasureIndex,width,measure.numerator,measure.denominator,measure.beatSubdivisions,measure.beatStates,measure.outerStates,measure.innerStates,measure.rhythmEditor,editing,selected]);if(key===lastKey)return;lastKey=key;const continuing=active.map(item=>({key:item.key,end:item.end}));clearHeads();notes=new Map();pulseAnchors=[];pulse.classList.remove('pulsing');host.replaceChildren();
  try{
   const poly=appMode==='polyrhythm',beats=poly?null:core.spell(measure,core.editorModel(measure)),rows=poly?[null]:[beats];
   const renderWidth=poly?Math.max(width,Math.max(measure.numerator,measure.denominator)*30+100):Math.max(width,...rows.map(row=>row.reduce((sum,b)=>sum+Math.max(46,b.count*25+12),84)));
   const height=poly?270:rows.length*140+18,renderer=new Flow.Renderer(host,Flow.Renderer.Backends.SVG);renderer.resize(renderWidth,height);const svg=host.querySelector('svg');svg.style.width='100%';svg.style.height='auto';const context=renderer.getContext();context.setFillStyle('#111').setStrokeStyle('#111');
   rows.forEach((row,rowIndex)=>{
    const voices=[],tuplets=[],beams=[];const stave=new Flow.Stave(2,18+rowIndex*140,renderWidth-4);stave.addClef('percussion');if(rowIndex===0)stave.addTimeSignature(`${measure.numerator}/${poly?4:measure.denominator}`);if(!poly&&rowIndex<rows.length-1)stave.setEndBarType(Flow.Barline.type.NONE);stave.setContext(context).draw();if(!poly)pulseLineY=stave.getYForLine(4);
    if(poly){
     const lanes=[];
     for(const [lane,count,states] of [['outer',measure.numerator,measure.outerStates],['inner',measure.denominator,measure.innerStates]]){
      const target=lane==='outer'?stave:new Flow.Stave(2,148,renderWidth-4).addClef('percussion').addTimeSignature(`${measure.numerator}/4`).setContext(context);if(lane==='inner')target.draw();
      const ns=Array.from({length:count},(_,i)=>makeNote('4',states[i]||0));const tuplet=lane==='inner'&&count!==measure.numerator?new Flow.Tuplet(ns,{num_notes:count,notes_occupied:measure.numerator,bracketed:true,ratioed:true}):null;
      const voice=new Flow.Voice({num_beats:measure.numerator,beat_value:4}).addTickables(ns);lanes.push({lane,states,ns,tuplet,voice,target});
     }
     const formatter=new Flow.Formatter();for(const item of lanes)formatter.joinVoices([item.voice]);formatter.format(lanes.map(item=>item.voice),renderWidth-90);
     for(const {voice,target,tuplet,ns,lane,states} of lanes){voice.draw(context,target);tuplet?.setContext(context).draw();ns.forEach((note,i)=>remember(note,`${lane}:${i}`,states[i]||0));}return;
    }
    const ns=[],entries=[],ties=[];for(const group of row){const groupNotes=[],tupletLanes=new Map();for(const piece of group.notes){const note=makeNote(String(piece.duration)+(piece.dots?'d':''),piece.state);if(piece.dots)Flow.Dot.buildAndAttach([note],{all:true});ns.push(note);groupNotes.push(note);entries.push({note,piece});if(piece.tuplet){const lane=tupletLanes.get(piece.beat)||[];lane.push(note);tupletLanes.set(piece.beat,lane);}if(piece.tie&&piece.state){const previous=entries.at(-2);if(previous?.piece.index===piece.index)ties.push(new Flow.StaveTie({first_note:previous.note,last_note:note,first_indices:[0],last_indices:[0]}));}}
     for(const [beat,lane] of tupletLanes){const ratio=group.notes.find(p=>p.beat===beat&&p.tuplet).tuplet;tuplets.push(new Flow.Tuplet(lane,{num_notes:ratio.count,notes_occupied:ratio.normal,bracketed:true,ratioed:ratio.count!==3}));}
     beams.push(...Flow.Beam.generateBeams(groupNotes,{groups:[new Flow.Fraction(group.length,measure.denominator)],beam_rests:true,show_stemlets:true,maintain_stem_directions:true}));}
    const total=row.reduce((sum,g)=>sum+g.length,0),voice=new Flow.Voice({num_beats:total,beat_value:measure.denominator}).addTickables(ns);voices.push(voice);new Flow.Formatter().joinVoices(voices).format(voices,renderWidth-90);voice.draw(context,stave);beams.forEach(b=>b.setContext(context).draw());tuplets.forEach(t=>t.setContext(context).draw());ties.forEach(t=>t.setContext(context).draw());
    for(const {note,piece} of entries){const element=note.getSVGElement();if(element){if(editing){const bounds=element.getBBox(),hit=document.createElementNS('http://www.w3.org/2000/svg','rect');hit.setAttribute('x',bounds.x-7);hit.setAttribute('y',bounds.y-5);hit.setAttribute('width',Math.max(24,bounds.width+14));hit.setAttribute('height',Math.max(24,bounds.height+10));hit.setAttribute('fill','transparent');hit.setAttribute('stroke','none');hit.style.pointerEvents='all';element.prepend(hit);}element.dataset.event=piece.index;element.classList.toggle('score-selected',editing&&selected===piece.index);element.setAttribute('tabindex',editing?'0':'-1');element.setAttribute('role','button');element.setAttribute('aria-label',(piece.state?'Note':'Silence')+' '+(piece.index+1));for(const head of element.querySelectorAll('.vf-notehead'))head.style.setProperty('--note-state-color',colors[piece.state]);element.addEventListener('click',()=>selectEvent(piece.index));element.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectEvent(piece.index);}});}
     const headBounds=element?.querySelector('.vf-notehead')?.getBBox();pulseAnchors.push({beat:piece.start,x:headBounds?headBounds.x+headBounds.width/2:note.getAbsoluteX()});const b=Math.floor(piece.start+1e-8),sub=Math.round((piece.start-b)*measure.beatSubdivisions[b]);remember(note,`${b}:${sub}`,piece.state);}

   });
   if(appMode==='metronome'){pulseAnchors.push({beat:measure.numerator,x:renderWidth-12});host.append(pulse);}fitScore();host.dataset.font='Bravura';host.dataset.measure=String(activeMeasureIndex);host.dataset.noteCount=String(notes.size);
   for(const item of continuing){const note=notes.get(item.key);if(isPlaying&&note?.state&&item.end>audioCtx.currentTime){for(const head of note.heads)head.classList.add('score-active-head');active.push({...note,...item});}}
  }catch(error){lastKey='';status('La partition de ce rythme ne peut pas être affichée.');console.error('Rhythm score:',error);}
 }
 function refresh(){if(!enabled||redraw)return;redraw=requestAnimationFrame(()=>{redraw=0;draw();});}
 function tick(){frame=0;if(!enabled)return;if(!isPlaying){cues=[];clearHeads();return;}const now=audioCtx?.currentTime||0;
  for(const item of active.filter(item=>now>=item.end))for(const head of item.heads)head.classList.remove('score-active-head');active=active.filter(item=>now<item.end);
  while(cues.length&&cues[0].time<=now){const cue=cues.shift();if(!isPlaying||cue.measure!==activeMeasureIndex)continue;draw();const note=notes.get(cue.key);if(cue.pulse)pulseNow(cue.beat);if(!note?.state||!cue.audible||now>=cue.end)continue;for(const head of note.heads)head.classList.add('score-active-head');active.push({...note,key:cue.key,end:cue.end});
   const head=note.heads[0];if(head){const bounds=head.getBoundingClientRect(),viewport=host.getBoundingClientRect();if(bounds.top<viewport.top+20||bounds.bottom>viewport.bottom-20)host.scrollTop+=bounds.top-viewport.top-host.clientHeight/2;if(bounds.left<viewport.left+20||bounds.right>viewport.right-20)host.scrollLeft+=bounds.left-viewport.left-host.clientWidth/2;}}
  if(isPlaying||cues.length||active.length)frame=requestAnimationFrame(tick);
 }
 function wake(){if(enabled&&!frame)frame=requestAnimationFrame(tick);}
 function enqueue(cue){cues.push(cue);cues.sort((a,b)=>a.time-b.time);if(cues.length>256)cues.splice(0,cues.length-256);wake();}
 const render=renderActiveMeasure;renderActiveMeasure=function(...args){const result=render.apply(this,args);pencil.hidden=!enabled||appMode!=='metronome';editor.hidden=!enabled||!editing||appMode!=='metronome';pulse.hidden=!enabled||appMode!=='metronome';renderEditor();layout();refresh();return result;};
 const subdivisions=renderSubdivisionDots;renderSubdivisionDots=function(...args){const result=subdivisions.apply(this,args);refresh();return result;};
 const visual=scheduleVisualUpdate;scheduleVisualUpdate=function(mIdx,sIdx,time,position){const result=visual.apply(this,arguments);const m=measures[mIdx],p=position||getBeatAndSub(m,sIdx);enqueue({measure:mIdx,beat:p.beat,key:`${p.beat}:${Math.round(p.subIndex/(p.subdivisions||m.beatSubdivisions[p.beat])*m.beatSubdivisions[p.beat])}`,time,end:time+(p.durationMs||getStepDurationMs(getEffectiveTempo(m),m.denominator,m.beatSubdivisions[p.beat]))/1000,audible:isSilentCycleAudible(),pulse:p.subIndex===0&&(m.denominator>=8?(m.numerator%3===0?p.beat%3===0:m.numerator>=5&&m.numerator%2?p.beat%2===0&&p.beat<m.numerator-2:true):true)});return result;};
 const polyVisual=schedulePolyVisualUpdate;schedulePolyVisualUpdate=function(mIdx,event,time){const result=polyVisual.apply(this,arguments),m=measures[mIdx],cycle=m.numerator*60/getEffectiveTempo(m);if(event.outer)enqueue({measure:mIdx,key:`outer:${event.outerIndex}`,time,end:time+cycle/m.numerator,audible:true});if(event.inner)enqueue({measure:mIdx,key:`inner:${event.innerIndex}`,time,end:time+cycle/m.denominator,audible:true});return result;};
 const stop=stopMetronome;stopMetronome=function(...args){const result=stop.apply(this,args);cues=[];clearHeads();pulse.classList.remove('pulsing');clearBurst();cancelAnimationFrame(frame);frame=0;refresh();renderEditor();return result;};
 async function setView(next){
  if(enabled===next&&(!next||Flow))return;enabled=next;partitionButton.setAttribute('aria-pressed',String(enabled));metronomeButton.setAttribute('aria-pressed',String(!enabled));partitionButton.classList.toggle('active',enabled);metronomeButton.classList.toggle('active',!enabled);panel.classList.toggle('score-view',enabled);pencil.hidden=!enabled||appMode!=='metronome';editor.hidden=!enabled||!editing||appMode!=='metronome';pulse.hidden=!enabled||appMode!=='metronome';renderEditor();layout();
  if(!enabled){clearBurst();clearHeads();cancelAnimationFrame(frame);frame=0;return;}
  status('Chargement de la partition…');try{await load();if(!enabled)return;lastKey='';draw();renderEditor();layout();wake();}catch(error){if(enabled)status(error.message);}
 }
 partitionButton.addEventListener('click',()=>setView(true));metronomeButton.addEventListener('click',()=>setView(false));
 new ResizeObserver(layout).observe(wrapper);new ResizeObserver(layout).observe(editor);
 window.RENAX_SCORE={get enabled(){return enabled;},refresh,get snapshot(){return {font:'Bravura',notes:notes.size,queued:cues.length,active:active.length};}};
})();
