import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.RENAX_PLAYWRIGHT||'playwright');
const root=path.resolve(new URL('../..',import.meta.url).pathname.replace(/^\/(\w:)/,'$1'));
const sample={version:1,activeProfile:'profile-guest',profiles:[{id:'profile-guest',name:'Mes morceaux',songs:[{id:'song-guest',name:'Morceau conservé',sections:[{id:'intro',label:'Intro',count:4,measure:{numerator:6,denominator:8,tempo:120,beatSubdivisions:[1,1,1,1,1,1],beatStates:[[3],[1],[1],[2],[1],[1]]}}]}]}]};
sample.profiles.push({id:'empty-profile',name:'Profil vide conservé',songs:[]});
function server(emulator){return http.createServer((req,res)=>{const name=decodeURIComponent(req.url.split('?')[0]);if(name==='/firebase-config.js'&&emulator){res.setHeader('Content-Type','application/javascript');return res.end(`export const firebaseConfig={apiKey:'demo-key',authDomain:'localhost',projectId:'demo-renax-backup',appId:'demo'};export const providers={email:true,google:false};export const appCheckSiteKey=null;export const emulator={host:'127.0.0.1',authPort:9099,firestorePort:8080};`);}const file=path.join(root,name);if(!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(file));});}
const local=server(false),cloud=server(true);await new Promise(r=>local.listen(8765,'127.0.0.1',r));await new Promise(r=>cloud.listen(8766,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:process.env.RENAX_CHROME||undefined,headless:true});
const open=async(context,port)=>{const p=await context.newPage();p.on('pageerror',error=>{console.error('PAGE ERROR',error.message);});await p.goto(`http://127.0.0.1:${port}/index2.html`);await p.waitForFunction(()=>window.RENAX_BACKUP);return p;};
const backup=async p=>{await p.locator('.song-tabs [data-pane="songs"]').click();await p.getByRole('button',{name:'Sauvegarde',exact:true}).click();};
const login=async(p,email,creating)=>{await backup(p);await p.getByLabel('E-mail',{exact:true}).fill(email);await p.getByLabel('Mot de passe',{exact:true}).fill('Test-only-password-2026!');await p.getByRole('button',{name:creating?'Créer un compte':'Se connecter',exact:true}).click();await p.waitForFunction(()=>RENAX_BACKUP.status.account&&RENAX_STORAGE.scope.startsWith('user:'),{timeout:30000});};
const synced=async p=>{await p.waitForFunction(()=>RENAX_BACKUP.status.message==='Synchronisé',{timeout:30000});};
const edit=async(p,name)=>{await p.evaluate(name=>{const library=JSON.parse(JSON.stringify(RENAX_SONGS.library));const song=library.profiles.flatMap(p=>p.songs)[0];song.name=name;RENAX_STORAGE.write(library);RENAX_SONGS.replaceLibrary(library);window.dispatchEvent(new Event('renax-library-edited'));},name);};
const names=async p=>p.evaluate(()=>RENAX_SONGS.library.profiles.flatMap(p=>p.songs.map(s=>s.name)));
try{
const guest=await browser.newContext({viewport:{width:1480,height:800}});await guest.addInitScript(value=>{if(!localStorage.getItem('renax-drums-songs-v1'))localStorage.setItem('renax-drums-songs-v1',JSON.stringify(value));},sample);
let transmissions=0;guest.on('request',req=>{if(/firestore.googleapis.com|identitytoolkit.googleapis.com|securetoken.googleapis.com|gstatic.com\/firebasejs/.test(req.url()))transmissions++;});const pg=await open(guest,8765);await backup(pg);assert.equal(await pg.getByRole('button',{name:'Se connecter',exact:true}).isEnabled(),true);assert.deepEqual(await names(pg),['Morceau conservé']);assert.equal(await pg.evaluate(()=>localStorage.getItem('renax-drums-songs-v1')),JSON.stringify(sample));await pg.reload();await pg.waitForFunction(()=>RENAX_BACKUP);assert.deepEqual(await names(pg),['Morceau conservé']);assert.equal(transmissions,0);console.log('Guest: migration, preserved legacy source, reload, no remote transmission PASS');await guest.close();
const a=await browser.newContext(),b=await browser.newContext();await a.addInitScript(value=>{if(!localStorage.getItem('renax-drums-songs-v1'))localStorage.setItem('renax-drums-songs-v1',JSON.stringify(value));},sample);
const pa=await open(a,8766),pb=await open(b,8766),email='renax-'+Date.now()+'@example.test';await login(pa,email,true);await synced(pa);assert.deepEqual(await names(pa),[]);await backup(pa);pa.once('dialog',d=>d.accept());await pa.getByRole('button',{name:'Importer les morceaux sans compte',exact:true}).click();await synced(pa);assert.deepEqual(await names(pa),['Morceau conservé']);assert(await pa.evaluate(()=>RENAX_SONGS.library.profiles.some(p=>p.name==='Profil vide conservé')));const profileCount=await pa.evaluate(()=>RENAX_SONGS.library.profiles.length);await backup(pa);pa.once('dialog',d=>d.accept());await pa.getByRole('button',{name:'Importer les morceaux sans compte',exact:true}).click();await synced(pa);assert.equal(await pa.evaluate(()=>RENAX_SONGS.library.profiles.length),profileCount);await login(pb,email,false);await synced(pb);assert.deepEqual(await names(pb),['Morceau conservé']);console.log('Two devices: explicit first import and remote library recovery PASS');
await edit(pa,'Version A');await synced(pa);await pb.waitForFunction(()=>RENAX_SONGS.library.profiles.some(p=>p.songs.some(s=>s.name==='Version A')));await synced(pb);
await b.setOffline(true);await edit(pb,'Version B hors connexion');const pending=await pb.evaluate(()=>JSON.stringify(RENAX_STORAGE.state.pending));assert(pending!=='{}');await edit(pa,'Version A concurrente');await synced(pa);
await b.setOffline(false);await pb.route('http://127.0.0.1:8080/**',route=>route.abort());await pb.reload();await pb.waitForFunction(()=>RENAX_BACKUP);assert.deepEqual(await names(pb),['Version B hors connexion']);assert((await pb.evaluate(()=>Object.keys(RENAX_STORAGE.state.pending))).length>0);await pb.waitForFunction(()=>RENAX_BACKUP.status.account,{timeout:30000});await pb.unroute('http://127.0.0.1:8080/**');await pb.evaluate(()=>RENAX_BACKUP.sync());console.log('After resume',await pb.evaluate(()=>({status:RENAX_BACKUP.status,scope:RENAX_STORAGE.scope,pending:Object.keys(RENAX_STORAGE.state.pending),conflicts:Object.keys(RENAX_STORAGE.state.conflicts)})));await pb.waitForFunction(()=>RENAX_BACKUP.status.message==='Conflit à résoudre',{timeout:30000});assert.equal((await pb.evaluate(()=>Object.values(RENAX_STORAGE.state.conflicts)))[0].remote.revision>=2,true);await backup(pb);await pb.getByRole('button',{name:'Conserver cet appareil',exact:true}).first().click();await synced(pb);await pa.waitForFunction(()=>RENAX_SONGS.library.profiles.some(p=>p.songs.some(s=>s.name==='Version B hors connexion')));console.log('Offline restart, persistent queue, concurrent conflict and explicit local resolution PASS');
await b.setOffline(true);await edit(pb,'Modification avant suppression');await pa.evaluate(()=>{const library=JSON.parse(JSON.stringify(RENAX_SONGS.library));for(const p of library.profiles)p.songs=[];RENAX_STORAGE.write(library);RENAX_SONGS.replaceLibrary(library);window.dispatchEvent(new Event('renax-library-edited'));});await synced(pa);await b.setOffline(false);await pb.evaluate(()=>RENAX_BACKUP.sync());await pb.waitForFunction(()=>RENAX_BACKUP.status.message==='Conflit à résoudre',{timeout:30000});assert((await pb.evaluate(()=>Object.values(RENAX_STORAGE.state.conflicts))).some(c=>c.remote.deleted));await backup(pb);for(const btn of await pb.getByRole('button',{name:'Conserver en ligne',exact:true}).all())await btn.click();await synced(pb);assert.deepEqual(await names(pb),[]);console.log('Offline edit versus remote tombstone: no silent resurrection PASS');
await backup(pa);await pa.getByRole('button',{name:'Historique / restaurer',exact:true}).click();pa.once('dialog',d=>d.accept());await pa.getByRole('button',{name:'Restaurer cette version',exact:true}).first().click();await synced(pa);assert.equal((await names(pa)).length,1);console.log('History restore with retained previous revisions PASS');
await backup(pa);await pa.getByRole('button',{name:'Se déconnecter',exact:true}).click();await pa.waitForFunction(()=>RENAX_STORAGE.scope==='guest');assert.deepEqual(await names(pa),['Morceau conservé']);await login(pa,'other-'+Date.now()+'@example.test',true);await synced(pa);assert.deepEqual(await names(pa),[]);console.log('Logout and account change: anonymous data and account A never transferred to B PASS');
await a.close();await b.close();
}finally{await browser.close();await new Promise(r=>local.close(r));await new Promise(r=>cloud.close(r));}
