import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.RENAX_PLAYWRIGHT||'C:/Users/renax/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(new URL('../..',import.meta.url).pathname.replace(/^\/(\w:)/,'$1'));
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.html')?'text/html':file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(file));});
await new Promise(r=>server.listen(8767,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.RENAX_CHROME||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const errors=[];
const open=async context=>{const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8767/index2.html');await p.waitForFunction(()=>window.RENAX_BACKUP);return p;};
const panel=async p=>{if(await p.locator('#mobileTabs [data-tab="seq"]').isVisible())await p.locator('#mobileTabs [data-tab="seq"]').click();await p.locator('.song-tabs [data-pane="songs"]').click();if(await p.getByRole('button',{name:'Sauvegarde',exact:true}).isVisible())await p.getByRole('button',{name:'Sauvegarde',exact:true}).click();};
try{
const corrupt=await browser.newContext();await corrupt.addInitScript(()=>localStorage.setItem('renax-index2-store-v1:guest','{damaged-source'));const pc=await open(corrupt);assert.equal(await pc.evaluate(()=>RENAX_STORAGE.healthy),false);assert.equal(await pc.evaluate(()=>localStorage.getItem('renax-index2-store-v1:guest')),'{damaged-source');await panel(pc);assert(await pc.getByRole('button',{name:'Exporter la source locale préservée'}).isVisible());await corrupt.close();
const normal=await browser.newContext({viewport:{width:1480,height:800}});const p=await open(normal);const before=await p.evaluate(()=>localStorage.getItem('renax-index2-store-v1:guest'));const quota=await p.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.startsWith('renax-index2-store-v1:'))throw new DOMException('Quota exceeded','QuotaExceededError');return original.call(this,k,v);};let thrown=false;try{RENAX_STORAGE.write(RENAX_SONGS.library);}catch{thrown=true;}Storage.prototype.setItem=original;return {thrown,healthy:RENAX_STORAGE.healthy};});assert.deepEqual(quota,{thrown:true,healthy:false});assert.equal(await p.evaluate(()=>localStorage.getItem('renax-index2-store-v1:guest')),before);await p.reload();await p.waitForFunction(()=>RENAX_BACKUP);assert(await p.evaluate(()=>RENAX_STORAGE.healthy));
const signatures=[[4,4,0],[3,4,0],[5,4,0],[6,4,0],[3,8,0],[6,8,2],[9,8,3],[12,8,4],[15,8,5],[18,8,6],[6,16,0],[12,16,0]];
for(const[n,d,strong]of signatures){await p.locator('#activeNumerator').selectOption(String(n));await p.locator('#activeDenominator').selectOption(String(d));assert.equal(await p.locator('#sequencerContainer .step').count(),n);assert.equal(await p.locator('.compound-strong').count(),strong);}
await p.locator('#activeNumerator').selectOption('4');await p.locator('#activeDenominator').selectOption('4');const states=await p.evaluate(()=>JSON.stringify(measures[0].beatStates));await p.locator('#playBtn').click();await p.waitForFunction(()=>isPlaying);await p.locator('#playBtn').click();await p.waitForFunction(()=>!isPlaying);assert.equal(await p.evaluate(()=>JSON.stringify(measures[0].beatStates)),states);
await panel(p);const out=path.resolve(root,'../../outputs');fs.mkdirSync(out,{recursive:true});await p.screenshot({path:path.join(out,'backup-desktop.png')});await p.setViewportSize({width:390,height:844});await panel(p);await p.screenshot({path:path.join(out,'backup-mobile.png')});assert(await p.locator('#backupAccount').isVisible());assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await normal.close();assert.deepEqual(errors,[]);console.log('PASS local corruption preserved, quota failure preserved, recovery, signature matrix, Start/Stop, unchanged accents, desktop/mobile backup UI');
}finally{await browser.close();await new Promise(r=>server.close(r));}
