import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.RENAX_PLAYWRIGHT||'C:/Users/renax/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(new URL('../..',import.meta.url).pathname.replace(/^\/(\w:)/,'$1'));
const measure={numerator:4,denominator:4,tempo:120,beatSubdivisions:[1,1,1,1],beatStates:[[3],[1],[1],[1]]};
const seed={version:1,activeProfile:'p1',profiles:[{id:'p1',name:'Premier répertoire',songs:[{id:'s1',name:'Morceau initial',sections:[{id:'a',label:'Intro',count:4,measure}]}]},{id:'p2',name:'Autre répertoire',songs:[{id:'s2',name:'Autre morceau',sections:[{id:'b',label:'Intro',count:2,measure}]}]}]};
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(file));});
await new Promise(r=>server.listen(8769,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.RENAX_CHROME||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{for(const [width,height]of [[1159,668],[390,844],[320,740]]){
  const context=await browser.newContext({viewport:{width,height}});await context.addInitScript(value=>localStorage.setItem('renax-drums-songs-v1',JSON.stringify(value)),seed);const p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8769/index.html');await p.waitForFunction(()=>window.RENAX_BACKUP);if(width<=1100)await p.locator('#mobileTabs [data-tab=seq]').click();await p.locator('.song-tabs [data-pane=songs]').click();
  await p.getByRole('button',{name:'Sauvegarde',exact:true}).click();assert.equal(await p.locator('#profilePane .backup-profile').count(),0);assert(await p.locator('.backup-json').isVisible());const backupBack=await p.locator('#profilePane .song-back').boundingBox();assert.equal(backupBack.width,96);assert.equal(backupBack.height,width<=1100?44:36);assert.equal(await p.locator('#profilePane .song-back').evaluate(e=>getComputedStyle(e,'::before').backgroundColor),'rgb(255, 107, 0)');await p.locator('#profilePane .song-back').click();
  await p.getByRole('button',{name:'Playlist',exact:true}).click();assert(await p.getByRole('button',{name:'Morceau initial',exact:true}).isVisible());assert.equal(await p.getByRole('button',{name:'Autre morceau',exact:true}).count(),0);const playlistBack=await p.locator('#songPane .song-back').boundingBox();assert.equal(playlistBack.width,backupBack.width);assert.equal(playlistBack.height,backupBack.height);assert.equal(await p.locator('#mp3ExportOpen').count(),1);assert.equal(await p.locator('#mp3ExportOpen').evaluate(e=>e.parentElement.parentElement.id),'songPane');
  await p.getByLabel('Playlist active',{exact:true}).selectOption('p2');assert(await p.getByRole('button',{name:'Autre morceau',exact:true}).isVisible());await p.getByRole('button',{name:'Autre morceau',exact:true}).click();const detailBack=await p.locator('#songPane .song-back').boundingBox();assert.equal(detailBack.width,backupBack.width);assert.equal(detailBack.height,backupBack.height);await p.locator('#songPane .song-back').click();
  p.once('dialog',d=>d.accept('Mon projet libre'));await p.getByRole('button',{name:'Nouvelle playlist',exact:true}).click();assert.equal(await p.getByLabel('Playlist active',{exact:true}).locator('option:checked').textContent(),'Mon projet libre');await p.getByRole('button',{name:'Nouveau morceau',exact:true}).click();await p.getByLabel('Titre du morceau',{exact:true}).fill('Composition neuve');await p.getByLabel('Titre du morceau',{exact:true}).press('Tab');await p.locator('#songPane .song-back').click();assert(await p.getByRole('button',{name:'Composition neuve',exact:true}).isVisible());p.once('dialog',d=>d.accept('Projet renommé'));await p.getByRole('button',{name:'Renommer',exact:true}).click();assert.equal(await p.getByLabel('Playlist active',{exact:true}).locator('option:checked').textContent(),'Projet renommé');
  const library=await p.evaluate(()=>JSON.parse(JSON.stringify(RENAX_SONGS.library)));assert.equal(library.profiles.length,3);assert.equal(library.profiles[0].songs[0].name,'Morceau initial');assert.equal(library.profiles[1].songs[0].name,'Autre morceau');assert.equal(library.profiles[2].songs[0].name,'Composition neuve');assert.equal(await p.getByRole('button',{name:/Historique|Restaurer/}).count(),0);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  const out=path.resolve(root,'../../outputs');fs.mkdirSync(out,{recursive:true});await p.screenshot({path:path.join(out,`navigation-playlists-${width}.png`)});await p.locator('#index2SettingsBtn').click();assert(await p.locator('#index2SettingsPanel').isVisible());assert.equal(await p.locator('#index2SettingsPanel').evaluate(e=>getComputedStyle(e).scrollbarColor),'rgb(0, 198, 217) rgb(17, 17, 22)');await p.screenshot({path:path.join(out,`settings-scrollbar-${width}.png`)});await p.locator('#index2SettingsClose').click();assert.deepEqual(errors,[]);await context.close();console.log(`${width}x${height}: equal orange back icons, back routes, free playlist create/rename/select, existing songs preserved, export action location, hidden history and dark scrollbar PASS`);
}}finally{await browser.close();await new Promise(r=>server.close(r));}
